[[plugin]]
id           = "evergaster/wlmirror"
name         = "WL Mirror"
version      = "1.0.2"
author       = "evergaster"
license      = "MIT"
icon         = "cast"
description  = "Prende/apaga wl-mirror para espejear un output desde el control center."
deprecated   = false
plugin_api   = 3
tags         = ["screen"]
dependencies = ["wl-mirror"]
